name: Deploy DAGs to Airflow

on:
  push:
    paths:
      - 'dags/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy DAGs to Airflow
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AIRFLOW_HOST }}
          username: ${{ secrets.AIRFLOW_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dags/"
          target: "/home/airflow/dags/"

      - name: Trigger DAG refresh
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AIRFLOW_HOST }}
          username: ${{ secrets.AIRFLOW_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Refreshing DAGs..."
            airflow dags list
