 name: SSH via Bastion to Airflow EC2
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.BASTION_IP }}
    username: ${{ secrets.BASTION_USER }}
    key: ${{ secrets.BASTION_KEY }}
    port: 22
    proxy_host: ${{ secrets.TARGET_IP }}
    proxy_username: ${{ secrets.TARGET_USER }}
    proxy_key: ${{ secrets.TARGET_KEY }}
    proxy_port: 22
    script: |
      cd /home/airflow/airflow/dags
      git pull origin main
