
name: Deploy DAGs to Airflow Server

on:
  push:
    branches: [main]  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 58.226.27.226
        username: root
        port: 2222
        key: ${{ secrets.AIRFLOW_SSH_KEY }}
        script: |
          cd /root//airflow/dags  # 예: /home/airflow/airflow-dags
          git pull origin main              # 최신 DAG 코드 가져오기
          sudo systemctl restart airflow-scheduler
          sudo systemctl restart airflow-webserver
