name: Deploy Airflow DAGs

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy DAGs
        run: |
          cp -r $GITHUB_WORKSPACE/dags/* /root/airflow/dags/

      - name: Restart Airflow (without systemctl)
        run: |
          pkill -f "airflow webserver" || true
          pkill -f "airflow scheduler" || true
          nohup airflow webserver --port 8080 > ~/airflow-webserver.log 2>&1 &
          nohup airflow scheduler > ~/airflow-scheduler.log 2>&1 &

