name: SSH Test

on: workflow_dispatch

jobs:
  test-ssh:
    runs-on: self-hosted
    steps:
      - name: Test SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 172.31.243.226
          username: root
          port: 2222
          key: ${{ secrets.AIRFLOW_SSH_KEY }}
          script: |
            echo "✅ SSH 접속 성공"
