name: Deploy Airflow DAGs

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy DAGs
        run: |
          cp -r $GITHUB_WORKSPACE/dags/* /root/airflow/dags/
          
      - name: Restart Airflow in Docker
        run: |
          sungbeen-airflow-webserver-1
          sungbeen-airflow-scheduler-1
