name: Deploy Airflow DAGs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Runner가 Airflow 서버에 설치되어 있어야 함

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest DAGs
        run: |
          cd /root/airflow/dags
          git pull origin main

      - name: Restart Airflow
        run: |
          sudo systemctl restart airflow-webserver
          sudo systemctl restart airflow-scheduler
